apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rn1m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rn1m
    app.kubernetes.io/part-of: e2e-nodejs
  name: devfile-sample-rn1m
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-rn1m
status:
  loadBalancer: {}
